# Generated by Django 2.2.6 on 2019-10-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='attraction',
            field=models.ManyToManyField(to='attraction.Attraction'),
        ),
    ]
