# Generated by Django 2.2.6 on 2019-10-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('core', '0002_touristspot_attraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='comentaries',
            field=models.ManyToManyField(to='comments.Comment'),
        ),
    ]
