# Generated by Django 2.2.6 on 2019-10-09 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adress', '0001_initial'),
        ('core', '0003_touristspot_comentaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristspot',
            name='adress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adress.Adress'),
        ),
    ]
