# Generated by Django 2.2.6 on 2019-10-09 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_touristspot_evaluation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='touristspot',
            old_name='comentaries',
            new_name='comment',
        ),
    ]
