# Generated by Django 2.2.6 on 2019-10-09 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='thecoment',
            new_name='the_comment',
        ),
    ]
