# Generated by Django 2.2.6 on 2019-10-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adress',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
